name: Build and Release XMRig

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake -y
          choco install nasm -y
          choco install msys2 -y

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            cmake
            git

      - name: Build XMRig (x64)
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DXMRIG_NO_DONATE=1 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/xmrig.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
