name: Build and Release XMRig (Windows .exe)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    name: Build XMRig for Windows (.exe)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure project (MSVC)
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DXMRIG_NO_DONATE=1

      - name: Build with MSVC
        run: |
          cmake --build build --config Release

      - name: Upload xmrig.exe to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/xmrig.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
