name: Build XMRig

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential automake libtool autoconf \
            libhwloc-dev libssl-dev libuv1-dev git

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-linux
          path: build/xmrig

  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout XMRig
      uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkg-config

    - name: Build libuv (static)
      run: |
        git clone https://github.com/libuv/libuv.git
        cd libuv
        mkdir build && cd build
        cmake .. -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release
        echo "LIBUV_INCLUDE=$PWD/../include" >> $GITHUB_ENV
        echo "LIBUV_STATIC=$PWD/Release/uv_a.lib" >> $GITHUB_ENV

    - name: Build XMRig (static libuv)
      run: |
        mkdir build && cd build
        cmake .. -G "MinGW Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_HWLOC=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DUV_INCLUDE_DIR="$LIBUV_INCLUDE" \
          -DUV_LIBRARY="$LIBUV_STATIC" \
          -DCMAKE_EXE_LINKER_FLAGS="-static"
        cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-static
        path: build/xmrig.exe

    - name: Upload to Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: build/xmrig.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

