
name: Build Static XMRig

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          base-devel
    - name: Build XMRig (static, use built-in FetchContent)
      shell: msys2 {0}
      run: |
        mkdir build && cd build
        cmake .. -G "MinGW Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_HWLOC=ON \
          -DBUILD_STATIC=ON \
          -DWITH_LIBUV=ON \
          -DWITH_TLS=ON \
          -DCMAKE_EXE_LINKER_FLAGS="-static"
        cmake --build . --config Release
        echo "======== BUILD DIR CONTENTS ========"
        ls -l
        find .
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-static
        path: |
          build/*.exe
          build/Release/*.exe
    - name: Upload to GitHub Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: build/xmrig.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
