name: Build XMRig

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential automake libtool autoconf \
            libhwloc-dev libssl-dev libuv1-dev git

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. -DWITH_CN_LITE=OFF -DWITH_CN_HEAVY=OFF \
                   -DWITH_RANDOMX=ON -DWITH_ARGON2=ON \
                   -DWITH_TLS=ON -DWITH_HTTP=ON \
                   -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-linux
          path: build/xmrig

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install build tools
        run: choco install cmake nasm python git -y
  
      - name: Setup vcpkg and libuv
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install libuv:x64-windows
  
      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
  
      - name: Build
        run: cmake --build build --config Release
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-windows
          path: build/Release/xmrig.exe


