name: Build XMRig

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential automake libtool autoconf \
            libhwloc-dev libssl-dev libuv1-dev git

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. -DUV_INCLUDE_DIR=path/to/libuv/include -DUV_LIBRARY=path/to/libuv.a

      - name: Build
        run: |
          cd build
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-linux
          path: build/xmrig

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build tools
        run: choco install cmake nasm python git -y
      - name: Setup vcpkg and install libuv
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install libuv:x64-windows
      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
            -DUV_INCLUDE_DIR="${{ github.workspace }}\vcpkg\installed\x64-windows\include" `
            -DUV_LIBRARY="${{ github.workspace }}\vcpkg\installed\x64-windows\lib\uv.lib" `
      - name: Build
        run: cmake --build build --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-windows-x86
          path: build/Release/xmrig.exe

